[[items]]
id = 'markdown-guide'
title = 'Markdown 书写指南'
subtitle = 'Markdown 是一种可以使用普通文本编辑器编写的标记语言，通过简单的标记语法，它可以使普通文本内容具有一定的格式。'
author = 'Yy'
date = '2016-02-12'

[[items]]
id = 'hello-world'
title = 'Hello world'
subtitle = '...'
author = 'xx'
date = '2016-02-09'